[pytest]

# Test files are inside the tests folder
testpaths = tests

# Automatically use verbose output and show print statements
addopts = -v -s

markers =
    smoke: smoke test scenarios
    regression: regression test scenarios
    login: login related scenarios